root-upgrader: Add network config files to syshook

diff --git a/recipes-support/root-upgrader/files/syshook b/recipes-support/root-upgrader/files/syshook
--- a/recipes-support/root-upgrader/files/syshook
+++ b/recipes-support/root-upgrader/files/syshook
@@ -3,7 +3,7 @@
 # Hook for custom upgrade steps.
 # Update config files or anything else on the new rootfs now
 # while it is still writable
-# This script is given the already mounted new rootfs as $1 
+# This script is given the already mounted new rootfs as $1
 # Returning 1 on failure will abort the upgrade.
 
 if [ ! -d ${1} ]; then
@@ -13,7 +13,7 @@ fi
 
 upgrade_mnt=${1}
 
-echo "Copying /etc/fstab"
+echo "  Copying /etc/fstab"
 
 cp /etc/fstab ${upgrade_mnt}/etc/fstab
 
@@ -27,7 +27,7 @@ fi
 grep -q -e '\s\/opt\s' /etc/fstab
 
 if [ $? -eq 0 ]; then
-    echo "Creating /opt directory"
+    echo "  Creating /opt directory"
     mkdir -p ${upgrade_mnt}/opt
 
     if [ $? -ne 0 ]; then
@@ -36,7 +36,7 @@ if [ $? -eq 0 ]; then
     fi
 fi
 
-echo "Copying /etc/hostname"
+echo "  Copying /etc/hostname"
 cp /etc/hostname ${upgrade_mnt}/etc/hostname
 
 if [ $? -ne 0 ]; then
@@ -44,16 +44,16 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-echo "Copying /etc/ssh/* files"
+echo "  Copying /etc/ssh/* files"
 mkdir -p ${upgrade_mnt}/etc/ssh
 cp --preserve=mode,ownership /etc/ssh/* ${upgrade_mnt}/etc/ssh/
 
 if [ $? -ne 0 ]; then
     echo "Error copying /etc/ssh files"
     exit 1
-fi 
+fi
 
-echo "Copying /etc/passwd and /etc/shadow"
+echo "  Copying /etc/passwd and /etc/shadow"
 
 # keep the old passwords
 cp --preserve=mode,ownership /etc/passwd ${upgrade_mnt}/etc/passwd
@@ -68,6 +68,30 @@ cp --preserve=mode,ownership /etc/shadow ${upgrade_mnt}/etc/shadow
 if [ $? -ne 0 ]; then
     echo "Error copying /etc/shadow"
     exit 1
+fi
+
+if [ -f /etc/wpa_supplicant.conf ]; then
+    echo "  Copying /etc/wpa_supplicant.conf"
+
+    cp --preserve=mode,ownership /etc/wpa_supplicant.conf ${upgrade_mnt}/etc/wpa_supplicant.conf
+
+    if [ $? -ne 0 ]; then
+        echo "Error copying /etc/wpa_supplicant.conf"
+        exit 1
+    fi
+fi
+
+if [ -f /etc/network/interfaces ]; then
+    echo "  Copying /etc/network/interfaces"
+
+    mkdir -p ${upgrade_mnt}/etc/network
+
+    cp --preserve=mode,ownership /etc/network/interfaces ${upgrade_mnt}/etc/network/interfaces
+
+    if [ $? -ne 0 ]; then
+        echo "Error copying /etc/wpa_supplicant.conf"
+        exit 1
+    fi
 fi
 
 exit 0
